# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ovs_Compute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('protocol', models.CharField(choices=[('tcp', 'tcp'), ('ssl', 'ssl')], default='tcp', max_length=3)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('port', models.CharField(default='6640', help_text='(TCP or SSL) port number to connect.', max_length=400)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
