# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs_servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovs_compute',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
